# Generated by Django 4.2.23 on 2025-06-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ncbi_chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(
                        choices=[
                            ("ncbi_api_key", "NCBI API Key"),
                            ("rate_limit", "API Rate Limit (requests per second)"),
                            ("max_concurrent_queries", "Maximum Concurrent Queries"),
                            ("cache_duration", "Cache Duration (seconds)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("parameter_value", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
    ]
