# Generated by Django 4.2.23 on 2025-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ncbi_chat", "0002_systemconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfiguration",
            name="parameter_name",
            field=models.CharField(
                choices=[
                    ("ncbi_api_key", "NCBI API Key"),
                    ("rate_limit", "API Rate Limit (requests per second)"),
                    ("max_concurrent_queries", "Maximum Concurrent Queries"),
                    ("cache_duration", "Cache Duration (seconds)"),
                    ("ollama_host", "Ollama API Host"),
                    ("ollama_model_general", "General Purpose Model"),
                    ("ollama_model_biomedical", "Biomedical Model"),
                    ("ollama_model_analysis", "Analysis Model"),
                    ("ollama_timeout", "Ollama Request Timeout (seconds)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
